services:
  hunyuan-api:
    build:
      context: ./hunyuan-docker
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./output:/root/output
    environment:
      # You MUST provide a valid Hugging Face token with access to tencent/HunyuanVideo
      # Create one at https://huggingface.co/settings/tokens
      - HF_TOKEN=${HF_TOKEN:-default_token_for_testing}
      - USE_CPU_OFFLOAD=true
      - FLOW_REVERSE=true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://localhost:8000/health > /dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s 