version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./output:/app/output
    env_file:
      - .env
    depends_on:
      - postgres
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 5001
    networks:
      - video-gen-network

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-video_generation}
    restart: unless-stopped
    networks:
      - video-gen-network
      
  # PostgreSQL admin interface (optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@example.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-admin}
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - video-gen-network
      
volumes:
  postgres-data:

networks:
  video-gen-network:
    driver: bridge 