spec:
  name: video-generator
  services:
  - name: backend
    git:
      branch: main
      repo_clone_url: https://github.com/destinpq/vg.git
    build_command: pip install -r backend/requirements.txt
    run_command: cd backend && python -m flask run --host=0.0.0.0
    envs:
    - key: FLASK_APP
      value: app.flask_app
    - key: FLASK_ENV
      value: production
    - key: PORT
      value: "8080"
    - key: HOST
      scope: RUN_TIME
      value: ${APP_URL}

  - name: frontend
    git:
      branch: main
      repo_clone_url: https://github.com/destinpq/vg.git
    build_command: cd frontend && npm install && npm run build
    run_command: cd frontend && npm start
    envs:
    - key: NODE_ENV
      value: production
    - key: NEXT_PUBLIC_API_URL 
      value: ${APP_URL}/api 