name: video-generator
region: nyc
services:
  - name: backend
    github:
      branch: main
      deploy_on_push: true
      repo: destinpq/vg
    source_dir: backend
    build_command: pip install -r requirements.txt
    run_command: python flask_main.py
    http_port: 8080
    instance_size_slug: basic-1x
    instance_count: 1
    health_check:
      http_path: /api/health
      period_seconds: 10
      timeout_seconds: 5
      failure_threshold: 3
      success_threshold: 1
    routes:
      - path: /api
    envs:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: flask_main
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8080
      - key: PYTHONUNBUFFERED
        value: "1"

  - name: frontend
    github:
      branch: main
      deploy_on_push: true
      repo: destinpq/vg
    source_dir: frontend
    build_command: npm install && npm run build
    run_command: npm start
    http_port: 3000
    instance_size_slug: basic-xs
    instance_count: 1
    routes:
      - path: /
    cors:
      allow_origins:
        - regex: .*
      allow_methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
    envs:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        scope: BUILD_TIME
        value: ${APP_URL}/api 